In [4]:
import pandas
import import_ipynb
import FeatureStore

X_train = FeatureStore.getTrainDataset(2)
y_train = FeatureStore.getTrainTarget(2)

[1. 1. 1. ... 0. 0. 0.]
<class 'numpy.ndarray'>


In [5]:
from sklearn.preprocessing import StandardScaler

#https://stackoverflow.com/questions/35723472/how-to-use-sklearn-fit-transform-with-pandas-and-return-dataframe-instead-of-num
def scaleDataFrame(dataframe, debugPrint = False):
    scaler = StandardScaler()
    scaled_features = scaler.fit_transform(dataframe)
    dataframe = pandas.DataFrame(scaled_features, index=dataframe.index, columns=dataframe.columns)
    
    #check
    if debugPrint == True:
        for column in dataframe:
            print("[%s] mean = %.4f, variance = %.4f" % 
                  (column, dataframe[column].mean(), dataframe[column].var()))
    
    return dataframe

In [ ]:
from sklearn import svm, datasets
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold

from sklearn.model_selection import cross_val_score

from datetime import datetime

# C = 1000.0 algorithm hangs!
C = [0.0001, 0.001, 0.01, 0.1, 1.0, 10.0, 100.0]
#C = {1.0}
#grid = {'C': np.power(10.0, np.arange(-4, 0))}

print (X_train.shape)
print (y_train.shape)
for penalty in C:
    print("trying C = " + str(penalty))
    kf = KFold(n_splits=3, shuffle=False, random_state=241)
    
    X_train = scaleDataFrame(X_train, debugPrint = False)

    clf = svm.SVC(C = penalty, kernel = 'linear', random_state=241)
    #N = 800
    #XX = X_train.iloc[:N, :]
    #yy = y_train[:N]
    XX = X_train
    yy = y_train
    print("from", datetime.now())
    scores = cross_val_score(clf, XX, yy, scoring='accuracy', cv=kf)
    print(scores)
    print(scores.mean())
    print("to", datetime.now())
    
    continue;
    for train_index, test_index in cv.split(X_train):
        #clf = svm.SVC(kernel='linear', random_state=241)
        clf = svm.SVC(C = 1.0, kernel = 'linear', verbose = True, random_state=241)
        #XX = X_train.loc[train_index, ['Return_1', 'AverageVolume_1']]
        XX = X_train.loc[train_index, :]
        yy = y_train[train_index]
        #print(train_index[:])
        #print(X_train[0:13])
        #print(XX.iloc[:20,:])
        print(XX.iloc[:20, 0:1])
        #print(yy[:10])
        
        print("XX type",type(XX))
        print(XX.shape)
        print(yy.shape)
        #XX.to_csv("XX.csv", sep = ";")
        print("fit start")
        clf.fit(XX.iloc[:100, 0:2], yy[:100])
        print("fit end")
        y_pred = clf.predict(X_train.iloc[:,0:2])
        print(y_pred)
        
        #clf.fit(X_train[train_index], y_train[train_index])
#gs = GridSearchCV(clf, grid, scoring='accuracy', cv=cv)
#gs.fit(X, y)

(1057, 6)
(1057,)
trying C = 0.0001
from 2019-11-13 16:44:05.126446
[0.57790368 0.58522727 0.61931818]
0.5941497124216671
to 2019-11-13 16:44:05.198446
trying C = 0.001
from 2019-11-13 16:44:05.203470
[0.57790368 0.58522727 0.61931818]
0.5941497124216671
to 2019-11-13 16:44:05.278468
trying C = 0.01
from 2019-11-13 16:44:05.282535
[0.57790368 0.58522727 0.61931818]
0.5941497124216671
to 2019-11-13 16:44:05.360449
trying C = 0.1
from 2019-11-13 16:44:05.365535
[0.57790368 0.58522727 0.61931818]
0.5941497124216671
to 2019-11-13 16:44:05.436446
trying C = 1.0
from 2019-11-13 16:44:05.440448
[0.57790368 0.58522727 0.61931818]
0.5941497124216671
to 2019-11-13 16:44:05.523476
trying C = 10.0
from 2019-11-13 16:44:05.527536
[0.57790368 0.58522727 0.61931818]
0.5941497124216671
to 2019-11-13 16:44:05.702446
trying C = 100.0
from 2019-11-13 16:44:05.710444
